[package]
name = "lab-api"
version = "0.3.0"
edition = "2021"

[dependencies]
axum = "0.7"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net"] }

[dev-dependencies]
serde_json = "1"
tower = { version = "0.4", features = ["util"] }
